"use strict";

const bcrypt = require("bcrypt");

module.exports = {
  async up(queryInterface, Sequelize) {
    const hash = await bcrypt.hash("admin123", 10);
    const hash2 = await bcrypt.hash("gerente123", 10);

    await queryInterface.bulkInsert(
      "period",
      [
        {
          name: "2022/2023",
          create_at: new Date(),
        },
        {
          name: "2023/2024",
          create_at: new Date(),
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "level",
      [
        {
          name: "Pre-Escolar",
          create_at: new Date(),
        },
        {
          name: "Primaria",
          create_at: new Date(),
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "userRole",
      [
        {
          name: "superadmin",
          create_at: new Date(),
        },
        {
          name: "gerencia",
          create_at: new Date(),
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "role",
      [
        {
          name: "Director",
          create_at: new Date(),
        },
        {
          name: "Sub-Director",
          create_at: new Date(),
        },
        {
          name: "Coordinador",
          create_at: new Date(),
        },
        {
          name: "Administrativo",
          create_at: new Date(),
        },
        {
          name: "Obrero",
          create_at: new Date(),
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "users",
      [
        {
          email: "daniel@gmail.com",
          password: hash,
          create_at: new Date(),
          role_user: 1,
        },
        {
          email: "naibys@gmail.com",
          password: hash2,
          create_at: new Date(),
          role_user: 2,
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "staff",
      [
        {
          ci: "9604885",
          name: "Naibys",
          last_name: "Paez",
          address: "Cabudare",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          birth_date: "16/8/1980",
          admission_date: "20/02/2004",
          phone: "04149876543",
          email: "naibys@gmail.com",
          role_id: 1,
          create_at: new Date(),
        },
        {
          ci: "15049800",
          name: "Orlando",
          last_name: "Parra",
          address: "Residencias La Mora",
          gender: "Masculino",
          birth_place: "Barquisimeto",
          birth_date: "07/11/1986",
          admission_date: "10/10/2004",
          phone: "04244406070",
          email: "parraorlando@gmail.com",
          role_id: 2,
          create_at: new Date(),
        },
        {
          ci: "12",
          name: "Marianela",
          last_name: "Aldao",
          address: "Calle 40. Carrera 23",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          birth_date: "19/09/1981",
          admission_date: "10/10/2015",
          phone: "04149870910",
          email: "mary123@gmail.com",
          role_id: 3,
          create_at: new Date(),
        },
        {
          ci: "15325462",
          name: "Nilmar",
          last_name: "Garcia",
          address: "Av. Libertador. Metropolitano Javier",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          birth_date: "10/7/1975",
          admission_date: "20/01/2004",
          phone: "04125605609",
          email: "garcianilmar@gmail.com",
          role_id: 4,
          create_at: new Date(),
        },
        {
          ci: "13190190",
          name: "Vladimir",
          last_name: "Gonzalez",
          address: "Barquisimeto",
          gender: "Masculino",
          birth_place: "Barquisimeto",
          birth_date: "10/7/1975",
          admission_date: "20/01/2022",
          phone: "04245671213",
          email: "vladimil@gmail.com",
          role_id: 5,
          create_at: new Date(),
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "grade",
      [
        {
          name: "2do nivel",
          section: "A",
          create_at: new Date(),
          education_level_id: 1,
          period_id: 1,
        },
        {
          name: "2do nivel",
          section: "B",
          create_at: new Date(),
          education_level_id: 1,
          period_id: 1,
        },
        {
          name: "3er nivel",
          section: "A",
          create_at: new Date(),
          education_level_id: 1,
          period_id: 1,
        },
        {
          name: "3er nivel",
          section: "B",
          create_at: new Date(),
          education_level_id: 1,
          period_id: 1,
        },
        {
          name: "1er grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "1er grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "2do grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "2do grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "3er grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "3er grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "4to grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "4to grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "5to grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "5to grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "6to grado",
          section: "A",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
        {
          name: "6to grado",
          section: "B",
          create_at: new Date(),
          period_id: 1,
          education_level_id: 2,
        },
      ],
      {}
    );
    await queryInterface.bulkInsert(
      "teacher",
      [
        {
          ci: "8765288",
          name: "Anny",
          last_name: "Montero",
          address: "Calle 51 con 29",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04146758909",
          email: "annnymonte@gmail.com",
          admission_date: "20/01/2022",
          birth_date: "07/11/1986",
          grade_id: 1,
          created_at: new Date(),
        },
        {
          ci: "14768567",
          name: "Yslaine",
          last_name: "Segovia",
          address: "Avenida Pedro Leon Torre. Calle 54",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04149881043",
          email: "Yslainesegovia@gmail.com",
          admission_date: "20/01/2004",
          birth_date: "10/7/1975",
          grade_id: 2,
          created_at: new Date(),
        },
        {
          ci: "18768997",
          name: "Norexi",
          last_name: "Piña",
          address: "Barrio Bolivar. Calle 8",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04141234545",
          email: "Norexipiña@gmail.com",
          admission_date: "20/09/2008",
          birth_date: "16/8/1980",
          grade_id: 3,
          created_at: new Date(),
        },
        {
          ci: "12993567",
          name: "Yasenia",
          last_name: "Garcia",
          address: "Barrio Union. Calle 1",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04146789090",
          email: "Yaseniagarcia@gmail.com",
          admission_date: "10/10/2004",
          birth_date: "19/09/1981",
          grade_id: 4,
          created_at: new Date(),
        },
        {
          ci: "19034594",
          name: "Nuris",
          last_name: "Torrealba",
          address: "Cabudare. Valle Hondo. Sector 3",
          gender: "Femenino",
          birth_place: "Maracay",
          phone: "04145459870",
          email: "nuristorrealba@gmail.com",
          admission_date: "10/10/2015",
          birth_date: "19/09/1982",
          grade_id: 5,
          created_at: new Date(),
        },
        {
          ci: "20304518",
          name: "Ana",
          last_name: "Martinez",
          address: "Av. Fuerzas Armadas. Calle 60",
          gender: "Femenino",
          birth_place: "Caracas",
          phone: "04141009090",
          email: "anamartinez123@gmail.com",
          admission_date: "20/02/2010",
          birth_date: "07/11/1990",
          grade_id: 6,
          created_at: new Date(),
        },
        {
          ci: "15789445",
          name: "Sarai",
          last_name: "Valera",
          address: "Calle 52. Carrera 24",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04245674895",
          email: "saraivalteacher@gmail.com",
          admission_date: "20/02/2015",
          birth_date: "07/11/1990",
          grade_id: 7,
          created_at: new Date(),
        },
        {
          ci: "20304598",
          name: "Leimary",
          last_name: "Montilla",
          address: "Calle 47. Carrera 30",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04261048900",
          email: "leimarmontilla@gmail.com",
          admission_date: "18/02/2020",
          birth_date: "01/08/1991",
          grade_id: 8,
          created_at: new Date(),
        },
        {
          ci: "23945999",
          name: "Nancy",
          last_name: "Bravo",
          address: "Brisas del Obelisco. Carrera 3",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04268908900",
          email: "nancybravo123@gmail.com",
          admission_date: "18/02/2022",
          birth_date: "01/09/1999",
          grade_id: 9,
          created_at: new Date(),
        },
        {
          ci: "13098765",
          name: "Luz",
          last_name: "Perez",
          address: "Barrio Union. Calle 6",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04245926006",
          email: "luzperez@gmail.com",
          admission_date: "18/02/2002",
          birth_date: "25/08/1969",
          grade_id: 10,
          created_at: new Date(),
        },
        {
          ci: "12356098",
          name: "Javier",
          last_name: "Chirinos",
          address: "Avenida Lara. Residencias Altamira",
          gender: "Masculino",
          birth_place: "Guanare",
          phone: "0412114880",
          email: "javierchirinosteacher@gmail.com",
          admission_date: "18/02/2008",
          birth_date: "20/04/1979",
          grade_id: 11,
          created_at: new Date(),
        },
        {
          ci: "16398400",
          name: "Aide",
          last_name: "Moreno",
          address: "Calle 54. Carrera 23. Residencias Lara Palace",
          gender: "Femenino",
          birth_place: "Valencia",
          phone: "04245451611",
          email: "aidemoreno10@gmail.com",
          admission_date: "10/04/2012",
          birth_date: "20/04/1982",
          grade_id: 12,
          created_at: new Date(),
        },
        {
          ci: "18398400",
          name: "Luis",
          last_name: "Guevara",
          address: "Av. Venezuela. Calle 42",
          gender: "Masculino",
          birth_place: "Barquisimeto",
          phone: "04247809898",
          email: "luisguevaraa@gmail.com",
          admission_date: "12/09/2015",
          birth_date: "20/04/1986",
          grade_id: 13,
          created_at: new Date(),
        },
        {
          ci: "21345112",
          name: "Marlene",
          last_name: "Alvarez",
          address: "Calle 51. Carrera 26",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04125706060",
          email: "alvarezmarlene@gmail.com",
          admission_date: "02/10/2018",
          birth_date: "24/12/1988",
          grade_id: 14,
          created_at: new Date(),
        },
        {
          ci: "16899090",
          name: "Maria",
          last_name: "Rodríguez",
          address: "Urb. El Ujano. Calle 9",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04241789010",
          email: "maferrodríguez@gmail.com",
          admission_date: "10/06/2020",
          birth_date: "03/03/1998",
          grade_id: 15,
          created_at: new Date(),
        },
        {
          ci: "13780980",
          name: "Lisbeth",
          last_name: "Perez",
          address: "Fuerzas Armadas. Calle 51",
          gender: "Femenino",
          birth_place: "Barquisimeto",
          phone: "04125637089",
          email: "perezlisbeth@gmail.com",
          admission_date: "02/10/2018",
          birth_date: "14/09/1978",
          grade_id: 16,
          created_at: new Date(),
        },
      ],
      {}
    );
    // await queryInterface.bulkInsert("", [{}], {});
    // await queryInterface.bulkInsert("", [{}], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("staff", null, {});
    await queryInterface.bulkDelete("role", null, {});
    await queryInterface.bulkDelete("userRole", null, {});
    await queryInterface.bulkDelete("user", null, {});
    await queryInterface.bulkDelete("grade", null, {});
    await queryInterface.bulkDelete("level", null, {});
    await queryInterface.bulkDelete("period", null, {});
  },
};
