import React from "react";

const AppLoader = () => {
  return (
    <>
      <div className="loadingio-spinner-eclipse-hw4seq2vdkc">
        <div className="ldio-pwo0kioqkmq">
          <div></div>
        </div>
      </div>
      <style jsx>{`
        @keyframes ldio-pwo0kioqkmq {
          0% {
            transform: rotate(0deg);
          }
          50% {
            transform: rotate(180deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }
        .ldio-pwo0kioqkmq div {
          position: absolute;
          animation: ldio-pwo0kioqkmq 1s linear infinite;
          width: 160px;
          height: 160px;
          border-radius: 50%;
          box-shadow: 0 4px 0 0 #143b64;
          transform-origin: 80px 82px;
        }
        .loadingio-spinner-eclipse-hw4seq2vdkc {
          width: 100vw;
          height: 100vh;
          margin-top: 25%;
          margin-bottom: 25%
          display: inline-block;
          overflow: hidden;
          background: #ffffff;
        }
        .ldio-pwo0kioqkmq {
          width: 100%;
          height: 100%;
          display: flex;
          justify-content: center;
          position: relative;
          transform: translateZ(0) scale(1);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-pwo0kioqkmq div {
          box-sizing: content-box;
        }
        /* generated by https://loading.io/ */
      `}</style>
    </>
  );
};

export default AppLoader;
