import React from "react";

const LoginLoader = () => {
  return (
    <>
      <div className="loadingio-spinner-rolling-wb5qu1mp89f">
        <div className="ldio-xg3u3vvzxwe">
          <div></div>
        </div>
      </div>
      <style jsx>{`
        @keyframes ldio-xg3u3vvzxwe {
          0% {
            transform: translate(-50%, -50%) rotate(0deg);
          }
          100% {
            transform: translate(-50%, -50%) rotate(360deg);
          }
        }
        .ldio-xg3u3vvzxwe div {
          position: absolute;
          width: 30px;
          height: 30px;
          border: 5px solid #fff;
          border-top-color: transparent;
          border-radius: 50%;
        }
        .ldio-xg3u3vvzxwe div {
          animation: ldio-xg3u3vvzxwe 1s linear infinite;
          top: 25px;
          left: 25px;
        }
        .loadingio-spinner-rolling-wb5qu1mp89f {
          width: 50px;
          height: 50px;
          display: inline-block;
          overflow: hidden;
          background: transparent;
        }
        .ldio-xg3u3vvzxwe {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(1);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-xg3u3vvzxwe div {
          box-sizing: content-box;
        }
        /* generated by https://loading.io/ */
      `}</style>
    </>
  );
};

export default LoginLoader;
